export const DEFAULT_INTERFACE_LANGUAGE = "en";
export const INTERFACE_LANGUAGE_STORAGE_KEY = "answerdocs.interfaceLanguage";

export const SUPPORTED_INTERFACE_LANGUAGES = ["en", "pt"] as const;

export type InterfaceLanguage = (typeof SUPPORTED_INTERFACE_LANGUAGES)[number];

export function normalizeInterfaceLanguage(
  value: unknown,
): InterfaceLanguage {
  return value === "pt" ? "pt" : DEFAULT_INTERFACE_LANGUAGE;
}

export const INTERFACE_COPY = {
  en: {
    common: {
      answerDocs: "AnswerDocs",
      backToChat: "Back to chat",
      cancel: "Cancel",
      confirm: "Confirm",
      copied: "Copied",
      delete: "Delete",
      deleting: "Deleting",
      edit: "Edit",
      email: "Email",
      english: "English",
      loading: "Loading",
      name: "Name",
      password: "Password",
      portuguese: "Portuguese",
      save: "Save",
      saving: "Saving",
    },
    account: {
      account: "Account",
      accountSettings: "Account settings",
      signIn: "Sign in",
      signOut: "Sign out",
      signedOut: "Signed out. You are using guest mode.",
    },
    auth: {
      welcomeBack: "Welcome back",
      createAccount: "Create your account",
      login: "Login",
      loginSummary:
        "Sign in to keep folders, chats, documents, and history saved.",
      signupSummary: "Start saving your workspace across folders and chats.",
      namePlaceholder: "Your name",
      emailPlaceholder: "you@example.com",
      passwordPlaceholder: "Your password",
      confirmPassword: "Confirm password",
      confirmPasswordPlaceholder: "Repeat your password",
      forgotPassword: "Forgot password?",
      forgotPasswordTitle: "Reset your password",
      forgotPasswordSummary:
        "Enter your account email and we will send a recovery link.",
      sendResetLink: "Send reset link",
      sendingResetLink: "Sending link",
      resetLinkSent:
        "If this email is registered, we will send a reset link.",
      backToLogin: "Back to login",
      requestNewResetLink: "Request a new link",
      resetPasswordTitle: "Set a new password",
      resetPasswordSummary: "Choose a new password for your account.",
      resetPasswordReady:
        "Your recovery link is ready. Set a new password below.",
      resetPasswordInvalid:
        "This reset link is invalid or expired. Request a new one.",
      newPassword: "New password",
      newPasswordPlaceholder: "At least 6 characters",
      updatePassword: "Update password",
      updatingPassword: "Updating password",
      resetPasswordSuccess:
        "Password reset successfully. Redirecting to login.",
      invalidEmail: "Enter a valid email address.",
      passwordRequirement: "Use at least 6 characters.",
      resetPasswordFailed:
        "Could not reset your password. Open the reset link again.",
      passwordsDoNotMatch: "Passwords do not match.",
      authFailed: "Authentication failed.",
      confirmation:
        "Account created successfully! We sent you a confirmation email. Please check your inbox to activate your account.",
      emailVerified:
        "Email verified successfully. Sign in to continue.",
      emailVerificationFailed:
        "We could not confirm this email link. Try signing in or request a new confirmation email.",
      incorrectLogin: "Email or password is incorrect.",
      existingAccount: "An account with this email already exists.",
      passwordCheck: "Check your password and try again.",
      emailCheck: "Check your email address and try again.",
      requestFailed: "Could not complete this request.",
    },
    workspace: {
      preparingChat: "Preparing chat session",
      preparingWorkspace: "Preparing workspace",
      foldersLabel: "Folders",
      loadingFolders: "Loading folders",
      noFolders: "No folders",
      newFolder: "New folder",
      guestMode: "Guest mode",
      guestNotice: "Sign in to save folders, chats, documents, and history.",
      openMenu: "Open menu",
      closeMenu: "Close menu",
      expandDocuments: "Expand document menu",
      collapseDocuments: "Collapse document menu",
      ready: "ready",
      selected: "selected",
      chats: "chats",
      documents: "Documents",
      upload: "Upload",
      paste: "Paste",
      title: "Title",
      titlePlaceholder: "Quarterly report",
      file: "File",
      selectFile: "Select file",
      changeFile: "Change file",
      fileHint: "PDF or .txt, up to 20 MB",
      fileTooLarge: "File exceeds the 20 MB limit per file.",
      text: "Text",
      textPlaceholder: "Paste document text here",
      indexDocument: "Index document",
      indexedFiles: "Indexed files",
      selectAll: "Select all",
      clear: "Clear",
      loadingDocuments: "Loading documents",
      noDocuments: "No documents indexed",
      chunks: "chunks",
      showFewerDocuments: "Show fewer documents",
      showMoreDocuments: "Show more documents",
      chatsTitle: "Chats",
      noFolderSelected: "No folder selected",
      temporaryGuestChat: "Temporary guest chat",
      newChat: "New",
      loadingChats: "Loading chats",
      noChats: "No chats yet",
      showFewerChats: "Show fewer chats",
      showMoreChats: "Show more chats",
      guestChatNotice:
        "To keep your history, create an account or sign in.",
      askDocuments: "Ask your documents",
      selectDocuments: "Select documents to ask from",
      noFolderDocuments: "No folder documents yet",
      noContext: "No context loaded yet",
      savedWorkspace: "Saved workspace",
      guestWorkspace: "Guest workspace",
      noQuestions: "No questions yet",
      emptyAnswers: "Indexed answers will appear here.",
      retrieving: "Retrieving context and drafting an answer",
      composerLabel: "Chat composer",
      composerPlaceholder:
        "Ask about your documents or paste a PDF/text context",
      indexingContext: "Processing document. Scanned pages may take longer.",
      ask: "Ask",
      dropPdf: "Drop PDF to add it to this folder",
      viewReferences: "View references",
      page: "Page",
      block: "Block",
      textBlock: "Text block",
      statusReady: "Ready",
      statusFailed: "Failed",
      statusIndexing: "Indexing",
      sessionNotReady: "The chat session is not ready yet.",
      openFolderBeforeAdding: "Open a folder before adding documents.",
      openFolderBeforeDeleting: "Open a folder before deleting documents.",
      chooseFile: "Choose a PDF or .txt file.",
      pasteTextBeforeIndexing: "Paste text before indexing.",
      indexedDocument: "Indexed",
      documentRemoved: "Document removed.",
      openChatBeforeAsking: "Create or open a chat before asking.",
      copyFailed: "Could not copy message.",
      folderNamePrompt: "Folder name",
      renameFolderPrompt: "Rename folder",
      deleteFolderConfirmSuffix: "and all chats and documents inside it?",
      newChatTitle: "New chat",
      renameChatPrompt: "Rename chat",
      deleteChatConfirmSuffix:
        "and its messages? Folder documents will stay available.",
      attachPdf: "Attach a PDF file.",
      addedToFolder: "Added",
      addedToFolderSuffix: "to this folder.",
      pastedDocumentContext: "Pasted document context",
      pastedPdfError:
        "Could not process the pasted PDF. Try uploading it or dragging it into the chat.",
    },
    profile: {
      title: "Account settings",
      subtitle: "Manage your profile, password, preferences, and account.",
      protectedMessage: "Sign in to edit your profile.",
      accountData: "Account data",
      accountDataDescription:
        "Keep your display name updated. Your email is shown for reference only.",
      displayName: "Display name",
      displayNamePlaceholder: "Your name",
      emailReadOnly: "Email cannot be changed here.",
      createdAt: "Account created",
      updateProfile: "Update profile",
      profileUpdated: "Profile updated.",
      security: "Security",
      securityDescription:
        "Confirm your current password before setting a new one.",
      currentPassword: "Current password",
      newPassword: "New password",
      confirmNewPassword: "Confirm new password",
      updatePassword: "Update password",
      passwordUpdated: "Password updated.",
      passwordRequirement: "Use at least 6 characters.",
      newPasswordDifferent: "Choose a new password that is different.",
      preferences: "Preferences",
      preferencesDescription:
        "Choose the language used by the interface. AI answers still follow your message language.",
      interfaceLanguage: "Interface language",
      dangerZone: "Danger zone",
      dangerDescription:
        "Deleting your account permanently removes your saved folders, chats, messages, references, and documents.",
      deleteAccount: "Delete account",
      deletePasswordLabel: "Current password",
      deleteConfirmationLabel: 'Type "DELETE" to confirm',
      deleteConfirmationPlaceholder: "DELETE",
      deleteWarning:
        "This action is permanent. Your saved workspace cannot be restored.",
      confirmDelete:
        "This will permanently delete your account and saved workspace. Continue?",
      deleteConfirmationRequired: 'Type "DELETE" to confirm account deletion.',
      accountDeleted: "Account deleted.",
      notAvailable: "Not available",
    },
  },
  pt: {
    common: {
      answerDocs: "AnswerDocs",
      backToChat: "Voltar ao chat",
      cancel: "Cancelar",
      confirm: "Confirmar",
      copied: "Copiado",
      delete: "Excluir",
      deleting: "Excluindo",
      edit: "Editar",
      email: "E-mail",
      english: "Inglês",
      loading: "Carregando",
      name: "Nome",
      password: "Senha",
      portuguese: "Português",
      save: "Salvar",
      saving: "Salvando",
    },
    account: {
      account: "Conta",
      accountSettings: "Configurações da conta",
      signIn: "Entrar",
      signOut: "Sair",
      signedOut: "Você saiu. Agora está usando o modo visitante.",
    },
    auth: {
      welcomeBack: "Bem-vindo de volta",
      createAccount: "Crie sua conta",
      login: "Entrar",
      loginSummary:
        "Entre para manter pastas, chats, documentos e histórico salvos.",
      signupSummary: "Comece a salvar seu workspace com pastas e chats.",
      namePlaceholder: "Seu nome",
      emailPlaceholder: "voce@exemplo.com",
      passwordPlaceholder: "Sua senha",
      confirmPassword: "Confirmar senha",
      confirmPasswordPlaceholder: "Repita sua senha",
      forgotPassword: "Esqueceu a senha?",
      forgotPasswordTitle: "Redefinir sua senha",
      forgotPasswordSummary:
        "Informe o e-mail da sua conta e enviaremos um link de recuperação.",
      sendResetLink: "Enviar link de recuperação",
      sendingResetLink: "Enviando link",
      resetLinkSent:
        "Se este e-mail estiver cadastrado, enviaremos um link para redefinir sua senha.",
      backToLogin: "Voltar ao login",
      requestNewResetLink: "Solicitar novo link",
      resetPasswordTitle: "Definir nova senha",
      resetPasswordSummary: "Escolha uma nova senha para sua conta.",
      resetPasswordReady:
        "Seu link de recuperação está pronto. Defina uma nova senha abaixo.",
      resetPasswordInvalid:
        "Este link de redefinição é inválido ou expirou. Solicite um novo.",
      newPassword: "Nova senha",
      newPasswordPlaceholder: "Pelo menos 6 caracteres",
      updatePassword: "Atualizar senha",
      updatingPassword: "Atualizando senha",
      resetPasswordSuccess:
        "Senha redefinida com sucesso. Redirecionando para o login.",
      invalidEmail: "Informe um e-mail válido.",
      passwordRequirement: "Use pelo menos 6 caracteres.",
      resetPasswordFailed:
        "Não foi possível redefinir sua senha. Abra o link de redefinição novamente.",
      passwordsDoNotMatch: "As senhas não coincidem.",
      authFailed: "Falha na autenticação.",
      confirmation:
        "Conta criada com sucesso! Enviamos um e-mail de confirmação. Verifique sua caixa de entrada para ativar sua conta.",
      emailVerified:
        "E-mail verificado com sucesso. Entre para continuar.",
      emailVerificationFailed:
        "Não foi possível confirmar este link de e-mail. Tente entrar ou solicite uma nova confirmação.",
      incorrectLogin: "E-mail ou senha incorretos.",
      existingAccount: "Já existe uma conta com este e-mail.",
      passwordCheck: "Verifique sua senha e tente novamente.",
      emailCheck: "Verifique seu e-mail e tente novamente.",
      requestFailed: "Não foi possível concluir esta solicitação.",
    },
    workspace: {
      preparingChat: "Preparando sessão do chat",
      preparingWorkspace: "Preparando workspace",
      foldersLabel: "Pastas",
      loadingFolders: "Carregando pastas",
      noFolders: "Nenhuma pasta",
      newFolder: "Nova pasta",
      guestMode: "Modo visitante",
      guestNotice: "Entre para salvar pastas, chats, documentos e histórico.",
      openMenu: "Abrir menu",
      closeMenu: "Fechar menu",
      expandDocuments: "Expandir menu de documentos",
      collapseDocuments: "Recolher menu de documentos",
      ready: "prontos",
      selected: "selecionados",
      chats: "chats",
      documents: "Documentos",
      upload: "Upload",
      paste: "Colar",
      title: "Título",
      titlePlaceholder: "Relatório trimestral",
      file: "Arquivo",
      selectFile: "Selecionar arquivo",
      changeFile: "Trocar arquivo",
      fileHint: "PDF ou .txt, até 20 MB",
      fileTooLarge: "O arquivo excede o limite de 20 MB por arquivo.",
      text: "Texto",
      textPlaceholder: "Cole o texto do documento aqui",
      indexDocument: "Indexar documento",
      indexedFiles: "Arquivos indexados",
      selectAll: "Selecionar todos",
      clear: "Limpar",
      loadingDocuments: "Carregando documentos",
      noDocuments: "Nenhum documento indexado",
      chunks: "blocos",
      showFewerDocuments: "Mostrar menos documentos",
      showMoreDocuments: "Mostrar mais documentos",
      chatsTitle: "Chats",
      noFolderSelected: "Nenhuma pasta selecionada",
      temporaryGuestChat: "Chat temporário de visitante",
      newChat: "Novo",
      loadingChats: "Carregando chats",
      noChats: "Nenhum chat ainda",
      showFewerChats: "Mostrar menos chats",
      showMoreChats: "Mostrar mais chats",
      guestChatNotice:
        "Para manter seu histórico salvo, crie uma conta ou entre na sua conta.",
      askDocuments: "Pergunte aos seus documentos",
      selectDocuments: "Selecione documentos para perguntar",
      noFolderDocuments: "Nenhum documento nesta pasta",
      noContext: "Nenhum contexto carregado",
      savedWorkspace: "Workspace salvo",
      guestWorkspace: "Workspace visitante",
      noQuestions: "Nenhuma pergunta ainda",
      emptyAnswers: "As respostas indexadas aparecerão aqui.",
      retrieving: "Buscando contexto e escrevendo uma resposta",
      composerLabel: "Campo de mensagem",
      composerPlaceholder:
        "Pergunte sobre seus documentos ou cole um PDF/texto como contexto",
      indexingContext:
        "Processando documento. PÃ¡ginas escaneadas podem demorar mais.",
      ask: "Enviar",
      dropPdf: "Solte o PDF para adicioná-lo a esta pasta",
      viewReferences: "Ver referências",
      page: "Página",
      block: "Bloco",
      textBlock: "Bloco de texto",
      statusReady: "Pronto",
      statusFailed: "Falhou",
      statusIndexing: "Indexando",
      sessionNotReady: "A sessão do chat ainda não está pronta.",
      openFolderBeforeAdding: "Abra uma pasta antes de adicionar documentos.",
      openFolderBeforeDeleting: "Abra uma pasta antes de excluir documentos.",
      chooseFile: "Escolha um PDF ou arquivo .txt.",
      pasteTextBeforeIndexing: "Cole um texto antes de indexar.",
      indexedDocument: "Indexado",
      documentRemoved: "Documento removido.",
      openChatBeforeAsking: "Crie ou abra um chat antes de perguntar.",
      copyFailed: "Não foi possível copiar a mensagem.",
      folderNamePrompt: "Nome da pasta",
      renameFolderPrompt: "Renomear pasta",
      deleteFolderConfirmSuffix: "e todos os chats e documentos dentro dela?",
      newChatTitle: "Novo chat",
      renameChatPrompt: "Renomear chat",
      deleteChatConfirmSuffix:
        "e suas mensagens? Os documentos da pasta continuarão disponíveis.",
      attachPdf: "Anexe um arquivo PDF.",
      addedToFolder: "Adicionado",
      addedToFolderSuffix: "a esta pasta.",
      pastedDocumentContext: "Contexto de documento colado",
      pastedPdfError:
        "Não foi possível processar o PDF colado. Tente enviar pelo upload ou arrastar para o chat.",
    },
    profile: {
      title: "Configurações da conta",
      subtitle: "Gerencie perfil, senha, preferências e conta.",
      protectedMessage: "Entre para editar seu perfil.",
      accountData: "Dados da conta",
      accountDataDescription:
        "Mantenha seu nome de exibição atualizado. O e-mail aparece apenas como referência.",
      displayName: "Nome de exibição",
      displayNamePlaceholder: "Seu nome",
      emailReadOnly: "O e-mail não pode ser alterado aqui.",
      createdAt: "Conta criada",
      updateProfile: "Atualizar perfil",
      profileUpdated: "Perfil atualizado.",
      security: "Segurança",
      securityDescription:
        "Confirme sua senha atual antes de definir uma nova.",
      currentPassword: "Senha atual",
      newPassword: "Nova senha",
      confirmNewPassword: "Confirmar nova senha",
      updatePassword: "Atualizar senha",
      passwordUpdated: "Senha atualizada.",
      passwordRequirement: "Use pelo menos 6 caracteres.",
      newPasswordDifferent: "Escolha uma nova senha diferente da atual.",
      preferences: "Preferências",
      preferencesDescription:
        "Escolha o idioma usado pela interface. As respostas da IA continuam seguindo o idioma da sua mensagem.",
      interfaceLanguage: "Idioma da interface",
      dangerZone: "Zona de perigo",
      dangerDescription:
        "Excluir sua conta remove permanentemente pastas, chats, mensagens, referências e documentos salvos.",
      deleteAccount: "Excluir conta",
      deletePasswordLabel: "Senha atual",
      deleteConfirmationLabel: 'Digite "DELETE" para confirmar',
      deleteConfirmationPlaceholder: "DELETE",
      deleteWarning:
        "Esta ação é permanente. Seu workspace salvo não poderá ser restaurado.",
      confirmDelete:
        "Isso excluirá permanentemente sua conta e seu workspace salvo. Continuar?",
      deleteConfirmationRequired:
        'Digite "DELETE" para confirmar a exclusão da conta.',
      accountDeleted: "Conta excluída.",
      notAvailable: "Não disponível",
    },
  },
} as const;

export type InterfaceCopy = (typeof INTERFACE_COPY)[InterfaceLanguage];

export function getInterfaceCopy(language: InterfaceLanguage) {
  return INTERFACE_COPY[language];
}
